# Site settings
title: "anıl iyidoğan"
email: iyidogan.anil@gmail.com
description: "bir bit bir blog"
baseurl: ""
url: "http://aniliyidogan.com/"
title_description: "bir gün bir bit ve bir blog akşam dolaşmaya çıkmış"
github_repository: https://github.com/aniliyidogan
post_limit: 5

# Social usernames/URLs
twitter_username: lifeis00FF00
github_username:  aniliyidogan
linkedin_link: https://tr.linkedin.com/in/aniliyidogan/

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
