# Site settings
title: "anıl iyidoğan"
email: anil@iyidogan.com
description: "bir bit bir blog"
baseurl: ""
url: "http://aniliyidogan.com/"
title_description: "bir gün bir bit ve bir blog akşam dolaşmaya çıkmış"
title_image: "https://pbs.twimg.com/profile_images/642027807929958401/Bfl95AG4.png"
disqus_account: aniliyidogan
github_repository: https://github.com/aniliyidogan
post_limit: 5

# Social usernames/URLs
twitter_username: lifeis00FF00
github_username:  aniliyidogan
linkedin_link: https://tr.linkedin.com/in/aniliyidogan/

# Footer
footer: 'gizli bilgi: tema için teşekkürler jacobtomlinson :)'

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
