# Site settings
title: "anıl iyidoğan"
email: anil@iyidogan.com
description: "bir bit bir blog"
baseurl: ""
url: "http://aniliyidogan.com/"
title_description: "bir gün bir bit ve bir blog akşam dolaşmaya çıkmış"
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/aniliyidogan
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: lifeis00FF00
github_username:  aniliyidogan
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/


# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
